### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#6]
# To-Do list

**Legend:**
* :smile: finished
* :construction: under construction
* :hourglass: waiting

## All the time
* Check that what we do separates SYE specific stuff from the more generic code

## Data
* [x] :smile: **House of Representatives** - We have data for the House of Representatives in EP (around 300 members), ~but it appears [under the name “National Assembly”](http://everypolitician.org/nigeria/). The National Assembly includes both the House of Representatives and the Senate. ([issue to rename it](https://github.com/everypolitician/everypolitician-data/issues/21869))([PR to rename it](https://github.com/everypolitician/everypolitician-data/pull/24138))~. Name changed.
* [x] :smile: **Senate** - We have data for the Senate in EP, but we can write a scraper for [this page](http://www.nass.gov.ng/mp/senate). ([issue to scrape it](https://github.com/everypolitician/everypolitician-data/issues/21871)) ([first PR for a scraper](https://github.com/everypolitician-scrapers/nigeria-senate/pull/1)) ([second PR in old scraper](https://github.com/everypolitician-scrapers/nigeria-national-assembly/pull/1)) ([EP-data PR](https://github.com/everypolitician/everypolitician-data/pull/24452))
* [x] :smile: **Governors** - We have data for the governors through [Struan’s scraper](https://morph.io/struan/nigerian_state_governors) (around 30 members) which seems similar to what is displayed now in [the Jekyll site](http://staging.shineyoureye.org/position/executive-governor/)

## Extra modules
* [ ] :construction: Breadcrumbs - *WIP*
* [x] Site and PU search box (just one box that does both things) - (in pages: democratic resources, posts, events, elections, about) ([implementation in the Jekyll version of the site](https://github.com/theyworkforyou/shineyoureye/blob/master/_plugins/jekyll_search.rb))
* [x] Google analytics
* [x] Comments (facebook or disqus)
* [x] :smile: Not a module but add a boolean `featured` field in the summaries frontmatter in prose.io

## Scripts
* [x] :smile: Finish deploy script to clone the prose repo, clone the sinatra repo, run the app, scrape the site and push to the static repo. Set up a webhook for prose?

## Pages
All those "*nice-to-have*" comments: It's probably better to leave them for when the rest of the site is finished

* [x] :smile: Posts - Maybe add a method to show a summary instead of the whole post contents.
From the requirements document:
> Nice to have would be the most current blogs from the current month on the news page with a side menu bar that allows you to see blogs organised via month + year ( eg July 2016)

* [x] :smile: Post

* [ ] 404 - easy ---> WE MAY NOT NEED IT :sparkles: 
* [x] :smile: About
* [x] :smile: Democracy resources
* [x] :smile: Government officials
* [x] :construction: Government officials/Senators - similar to reps
* [x] :smile: Government officials/Representatives
* [x] Government officials/Governors - similar to reps. May need to interact with morph API to get the data or add a webhook to download the csv everytime the file changes?
* [x] :smile: Places. the links point to the reps and senators pages.
* [x] :construction: Places/subpages the official site has three subpages more. They are all static pages that render EP data.
* [x] :construction: Place page

* [x] :smile: Events. From the document:
> Nice to have would be the most current events from the current month on the events page with a side menu bar that allows you to see events organised via month + year ( eg July 2016)
> Nice to have would be a calendar for events.

* [x] :smile:  Person page
The url adds the house slug, but the official site doesn't have it. We must remove it in the route. Also, check the requirements document and the official site as there are more things than in the Jekyll site. We also need to implement:
  * [x] :construction: summary

* [x] :smile: Home

* [x] :smile: Elections. From the requirements document:
> Desirable: Links to pages in the desirable section on voting information, Past Elections and re-runs.

* [x] :construction: Elections/subpages - According to the document, seems like they want them listed in a submenu dropdown. They are all static pages edited by them, so will be available on prose.

## Other

* Map Pombola slugs to person pages
* Add coveralls :heavy_check_mark: 
* Add metrics
* Add rubocop :heavy_check_mark: 
* PR to prose to fix filenames saved with a date?
* Tables in markdown
* Update README and also add relevant badges :heavy_check_mark: 
* html validation?

## To think about

* Summaries: We can save them with the member id as filename, then add an edit button in the person page. Prose gives you a nice url pointing to the edit page of a document. This url could be passed in the person page inside of an edit button that they can click to edit a person summary. If you are not logged in you can edit but not save. We would have to think if there can be any security issues with access although that may be handled by github (access permissions to repos) :heavy_check_mark: 
* ~How to extract a gem from viewer-sinatra shared code. We don't need any of the pages there except maybe the TermTable page, but the PersonCard class seems like it is waiting to be simplified.~
* Create a rake task that checks out a specific sha of the prose directory before running the tests? or leave our prose directory always at that sha? :heavy_check_mark: 
* How to import Struan's governors :heavy_check_mark: 

## What could be extracted into a parliament monitoring site gem
Probably only just what's in the lib folder, so avoid having SYE specific stuff entangled with the code there?
Another thought: We could make some kind of generator like the ones you can build with [yeoman](http://yeoman.io/). then we could put the generator into a gem, and just do something like `pm-site-generator new sitename`, just as Jekyll provides `jekyll new sitename`. That would generate a sinatra skeleton with our extra pm stuff. We could still move some of the code inside `lib` to tiny gems

## Things to maybe implement in the future:
* These can be part of the summary: :heavy_check_mark: 
    * [ ] executive_positions,
    * [ ] job_history and
    * [ ] education
* If this app succeeds, it would be nice to have [a documentation site like middleman's one](https://middlemanapp.com/basics/install/) in a `gh-pages` branch
* It would also be nice to have a style guide for the site, like https://stuffandnonsense.co.uk/blog/about/designing-inspired-style-guides-presentation-slides-and-transcript

**Comment by mhl** [comment]
These are mostly addressed now, and I think the other requirements from our partners should be represented by other tickets.
